### ISSUE TITLE
PHP 7.0 requirement not set in composer.json

### ISSUE THREAD

**Issue by czkit** [OXIDprojects/oxid-module-internals#100]
The module "oxid-module-internals" is compatible with OXID 6.0 (which have as requirement PHP 5.6) but in the code are using features from PHP7.0

for example in version 1.5.2:  
oxideshop/vendor/oxid-community/moduleinternals/Core/FixHelper.php $iPosition = $aValue['position'] ?? 1;
and other two places

in version 2.0.0 is also at least one place. 

The code should be changed to be compatible to PHP5.6 or the requirement of PHP7.0 should be set in modules composer.json

**Comment by keywan-ghadami-oxid** [comment]
https://github.com/OXIDprojects/oxid-module-internals/pull/101

**Comment by alfredbez** [comment]
This was fixed with #101
