### ISSUE TITLE
Empty Array on Admin Startpage

### ISSUE THREAD

**Issue by gaertnermarkus** [OXIDprojects/oxid-module-internals#123]
https://github.com/OXIDprojects/oxid-module-internals/blob/57f330d8edce4352471cab43e601023fa9f82ffe/Controller/Admin/NavigationController.php#L46

![Anmerkung 2020-01-02 103734](https://user-images.githubusercontent.com/3882322/71660694-2cc39100-2d4c-11ea-8b1d-af18d9cd065f.png)

**Comment by gaertnermarkus** [comment]
Maybe there is no array, or it is empty. But this create a permanent nonsensical item.

**Comment by alfredbez** [comment]
See also: https://github.com/OXIDprojects/oxid-module-internals/pull/115#issuecomment-567983589

**Comment by alfredbez** [comment]
fixed in #124
