### ISSUE TITLE
Upgrade from 1.0 to 1.1 not possible

### ISSUE THREAD

**Issue by keywan-ghadami-oxid** [OXIDprojects/oxid-module-internals#13]
reported: starting from Tag v1.1.0 (blank pages, segfaults) 
going back to 1.0.x helped

**Comment by keywan-ghadami-oxid** [comment]
related to https://github.com/OXIDprojects/oxid-module-internals/issues/12

**Comment by smxsm** [comment]
We experienced this for 4 staging shops this week, the only change was the updated module from 1.0.x to 1.1.x. All the shops were offline, in some even the backend wasn't working. Thankfully, we didn't deploy any live shop this week :) 
Looks like it was an endless loop, leading to max. execution time and/or memory limit exceptions, we had to delete all module data from oxconfig and then activate all the modules again.
Downgrading to 1.0.1 and re-deploying also helped.

**Comment by keywan-ghadami-oxid** [comment]
Should be fixed with version 1.2.1
