### ISSUE TITLE
Optimize issue detection in module list

### ISSUE THREAD

**Issue by adriankirchner** [OXIDprojects/oxid-module-internals#32]
IMHO there are two parts with potential to optimize issue detection:

1. [EDIT by Keywan] moved to https://github.com/OXIDprojects/oxid-module-internals/issues/35
2. Don't check for active settings not defined in metadata.php
After enabling the [ddoewysiwyg module](https://github.com/OXID-eSales/ddoe-wysiwyg-editor-module) the "Issue found!" flag persists. This is because this module registers two config values ([1](https://github.com/OXID-eSales/ddoe-wysiwyg-editor-module/blob/8c0ffda334d120e813d8c52e92784c7a79d47dab/Core/Events.php#L119), [2](https://github.com/OXID-eSales/ddoe-wysiwyg-editor-module/blob/8c0ffda334d120e813d8c52e92784c7a79d47dab/Core/Events.php#L185)) in the `onActivate` event which aren't defined in the metadata.php. Either this is bad practice and `ddoewysiwyg` should get fixed or the following part should be removed or mitigated to not raise the "Issue found!" flag:
https://github.com/OXIDprojects/oxid-module-internals/blob/3ef518018b36f7b4944dbca7e8202ed5ef19afdb/Core/InternalModule.php#L429-L431

**Comment by keywan-ghadami-oxid** [comment]
fixed, by ignoring additional settings not listed in metadata
