### ISSUE TITLE
Align module version with release version

### ISSUE THREAD

**Issue by adriankirchner** [OXIDprojects/oxid-module-internals#33]
https://github.com/OXIDprojects/oxid-module-internals/blob/3ef518018b36f7b4944dbca7e8202ed5ef19afdb/metadata.php#L52
Maybe this could be automated in the release process or is this divergence intended?

**Comment by keywan-ghadami-oxid** [comment]
good Idea, I think that could be useful for all modules, I am thinking about
```
     'version'     => 'composer', 
```
and having automatically putting in the installed version
