### ISSUE TITLE
feature: accordion on the overview page

### ISSUE THREAD

**Issue by keywan-ghadami-oxid** [OXIDprojects/oxid-module-internals#54]
the overview page lists all modules with all the details resulting in long list.
It would be useful to have only the title of the module unless you open it or unless it some issues and is automatically opened.

**Comment by gaertnermarkus** [comment]
I like this idea. Yes, and there is an issue it will be open for this module.
Next time, i can work on it.

We had the problem in some 4.x Shop that during installation the config crash, or some modules were disabled from unknow reason. And it waste at lot of time to activate or check up to 20 or more models. To have a overview about all modules, i created this page.
Now with the version 6.x and the new checks inside oxid-moduls-internals, maybe this page is not more necessary.
But until now, we havn't updated so much huge shops to 6.x, so  i can't say anythink about this.

**Comment by keywan-ghadami-oxid** [comment]
Thank you for feedback, the accordion function is done and will be released with 2.0.
Broken modules will be automatically opened on that page.

About the automatic disabling of modules you had trouble with, maybe module internals is someday able to improve that see https://github.com/OXIDprojects/oxid-module-internals/issues/12
