### ISSUE TITLE
Blocks: No Style for active flag in checkconsistency.tpl

### ISSUE THREAD

**Issue by gaertnermarkus** [OXIDprojects/oxid-module-internals#61]
For these active flag, there is no style available.

![bildschirmfoto vom 2019-01-07 um 08 43 37](https://user-images.githubusercontent.com/3882322/50755227-ba16f700-1258-11e9-80ea-6bfd3ef15faa.png)
![bildschirmfoto vom 2019-01-07 um 08 44 44](https://user-images.githubusercontent.com/3882322/50755229-ba16f700-1258-11e9-8ce2-267ce00c8a7d.png)

**Comment by keywan-ghadami-oxid** [comment]
fixed
