### ISSUE TITLE
Empty Status Page after installation via composer

### ISSUE THREAD

**Issue by gaertnermarkus** [OXIDprojects/oxid-module-internals#62]
A module is installed with composer.
First time after installation, the module title in Backend contains the message 'fixed'. But the status-Page in Backend for this modul ist empty(a white page but without an exception).

The file oxideshop.log contains some new entries, but they looks normal:
[2019-01-07 15:27:51] OXID Logger.ERROR: abc_module fixing module extensions [] []
[2019-01-07 15:27:51] OXID Logger.ERROR: abc_module fixing templates [] []
[2019-01-07 15:27:51] OXID Logger.ERROR: abc_module fixing module version from  to 4.0.0.0 [] []
[2019-01-07 15:27:51] OXID Logger.ERROR: abc_module fixing module events [] []

In Checkconsistency, the new modul isn't listed.

But after the module activation, all is fine for the status page and Checkconsistency.

Looks like a bug?

**Comment by keywan-ghadami-oxid** [comment]
modules that are not activated are not checked see https://github.com/OXIDprojects/oxid-module-internals/issues/35.
Anyway I like to keep this issue to improve the status page

**Comment by gaertnermarkus** [comment]
okay i see.
But in my opinion this is to late to check a module. I use this module in this three cases:
- in module development, even whe it's not installed (are the files at the right folder, will they recognize by the shop )
- to check a (third party/legacy) module before installation (contains the packe all the files from metadata.php, it is happend more often then you want to know)
- to check and repair the module status when the module is still installed

Mayby there is a way to enable/disable this check in the configuration?
But i/we need this check before the activation.

**Comment by keywan-ghadami-oxid** [comment]
ok I undersrand the usecase. some checks must be refactored to work on disabled modules, and we may need a setting as you suggested.

**Comment by keywan-ghadami-oxid** [comment]
this was fix by nitin
