### ISSUE TITLE
Empty version - after Installation new module

### ISSUE THREAD

**Issue by gaertnermarkus** [OXIDprojects/oxid-module-internals#68]
A new module is installed. 
In this case, there is no from-Version inside the logmessage:
'ModuleXyz fixing module version from  to 2.0.0.0 [] []'

This message is not wrong. But it looks like there was an error. 
Is it possible to check if it's a new installation? Make it sense to add a second sentence like - 'New installation, no former Version set'?

https://github.com/OXIDprojects/oxid-module-internals/blob/097f5d0a9498446f8b18d123d5123b39a13d680c/Core/ModuleStateFixer.php#L220

**Comment by keywan-ghadami-oxid** [comment]
fixed in https://github.com/OXIDprojects/oxid-module-internals/pull/69
